### ISSUE TITLE
MDL support?

### ISSUE THREAD

**Issue by gh1593** [LogicAndTrick/sledge-formats#1]
Very nice and easy to use, would like to see mdl supported, so far what I need is to read mdl infos, like material and texture names, so I can find them for this mdl automatically, don't know how to do that myself though.

**Comment by LogicAndTrick** [comment]
I won't have time to add MDL support to this project for a while, but you might be able to use the Sledge code for MDL loading: https://github.com/LogicAndTrick/sledge/tree/master/Sledge.Providers/Model/Mdl10/Format
It'll need some changes to work without all the related Sledge libraries, though.

**Comment by gh1593** [comment]
Very nice! I'll give it a try, thanks!
