### ISSUE TITLE
Support creating VTF files

### ISSUE THREAD

**Issue by WeirdOddz** [LogicAndTrick/sledge-formats#13]
I'm trying to make a nextbot generator but I couldn't figure out how to convert a png to vtf. I decided to post this here so that this can maybe could get added.

**Comment by LogicAndTrick** [comment]
The VTF format only supports reading, not creating new ones. Changing issue description.

**Comment by LogicAndTrick** [comment]
VTF creation added with version 1.1.0 and the `Sledge.Formats.Texture.ImageSharp` extension library.

Code looks like this:
```cs
var img = Image.Load(@"path/to/some.png");
var vtf = img.ToVtfFile(new VtfImageBuilderOptions { AutoResizeToPowerOfTwo = true });
using var file = File.OpenWrite(@"path/to/some.vtf);
vtf.Write(file);
```
