### ISSUE TITLE
Properties dictionary wrapper does not handle replacement of SortedProperties list

### ISSUE THREAD

**Issue by SamVanheer** [LogicAndTrick/sledge-formats#27]
When replacing the SortedProperties list on a `Sledge.Formats.Map.Objects.Entity` object the `Properties` dictionary still wraps the original list instead of the new list.

Either the setter needs to be removed or the setter should recreate the wrapper as well (which may leave dangling references to the old wrapper).

**Comment by LogicAndTrick** [comment]
Thanks :)
No release for this one for now since it's minor, will include in the next one
