### ISSUE TITLE
RMF v1.6 Inconsistent 'Face' structure

### ISSUE THREAD

**Issue by Duude92** [LogicAndTrick/sledge-formats#39]
So couple of month ago I've worked on prefab feature, and used [sledge-formats](https://github.com/LogicAndTrick/sledge-formats) library for it.
I noticed, that prefab planes uses wrong texturing shifts\rotation. Initially I thought it was confused for every RMF format, so I just used a [trick ](https://github.com/Duude92/hammertime/commit/c3062bbd76a9924361889940505d1313ff4c29f8#diff-256c70f5bcdc5abba544f13ab8472440bd89431eee0934e7916005258970345b)to route sledge-formats 'Face' fields to 'Sledge.BspEditor.Primitives.MapObjectData.Face'
![image](https://github.com/user-attachments/assets/2259b221-30b0-4ba7-bf4c-1c4e26d9dc94)
But recently I've returned to that issue, and found that wrong structure applied only for v1.6 (I've used VHE 3.4 (steam version) built-in prefabs 'computers', and 'Usable Objects' packs are 1.6 version, when others seems to be fine)
![image](https://github.com/user-attachments/assets/849e2c40-51e0-4dbc-a8bb-4175cae0d749)
(Screenshot above is made with routing 'as intended to be')
![image](https://github.com/user-attachments/assets/139daab2-89b2-44f8-92e4-aea21b490213)
(Added same prefabs with 'proper' routing)
Since I cant find specification description other than THWL website - I cant prove i'm right or wrong
It might be even more confusing, if you notice, that VHE 3.4 has the same issue, so the problem could be hidden deeper.
![image](https://github.com/user-attachments/assets/b64cfa5a-5925-481f-8f1c-cf513c67df06)

**Comment by LogicAndTrick** [comment]
Thanks for the bug report, I managed to replicate it and found it was loading the values in the wrong order for rmf 1.8 and lower. Should be fixed in the latest version now.
