### ISSUE TITLE
Incorrect handling of // in serialized objects

### ISSUE THREAD

**Issue by 13xforever** [LogicAndTrick/sledge-formats#6]
Right now `SerializedObjectFormatter.CleanLine()` truncates anything after `//` token even if it's inside a valid string (such as URL).
It should be only removed if it's outside the string or the sole content of the line.

Example:

```text
"web"
{
	"WebFav0_URL"		"https://www.google.com/"
	"WebFav0_Name"		"Google"
}
```

**Comment by LogicAndTrick** [comment]
Thanks for the report, it should be fixed now in 1.0.3. I rewrote the parser, but the tests still pass so hopefully it doesn't break compatibility.
